# Generated by Django 6.1 on 2026-08-07 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingrediente_plato_plan_componente_comida'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DES', 'Desayuno'), ('MM', 'Media Mañana'), ('ALM', 'Almuerzo'), ('MT', 'Media Tarde'), ('CEN', 'Cena')], max_length=3)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='api.plan')),
                ('platos', models.ManyToManyField(related_name='tiempos_comida', to='api.plato')),
            ],
        ),
        migrations.DeleteModel(
            name='Comida',
        ),
    ]
