# Generated by Django 6.1 on 2026-08-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tiempocomida_delete_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='objetivo_plan',
            field=models.CharField(choices=[('0.8', 'Perdida de peso'), ('1.0', 'Mantenimiento'), ('1.2', 'Ganancia muscular')], max_length=3),
        ),
    ]
