# Generated by Django 6.1 on 2026-08-07 22:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plan_objetivo_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pliegue_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pliegue_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pliegue_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad_fisica', models.CharField(choices=[('1.2', 'Sedentario (sin ejercicio)'), ('1.375', 'Ligero (ejercicio 1-3 días a la semana)'), ('1.55', 'Moderado (ejercicio 3-5 días a la semana)'), ('1.725', 'Muy activo (ejercicio 6-7 días a la semana)'), ('1.9', 'Extremadamente activo (ejercicio intenso 2 veces al día)')], default='1.2', max_length=5)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='api.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='medicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='api.medicion'),
        ),
    ]
