# Generated by Django 6.1 on 2026-08-07 22:16

from datetime import date

from django.db import migrations


def crear_medicion_inicial(apps, schema_editor):
    Paciente = apps.get_model('api', 'Paciente')
    Medicion = apps.get_model('api', 'Medicion')
    Plan = apps.get_model('api', 'Plan')

    for paciente in Paciente.objects.all():
        medicion = Medicion.objects.create(
            paciente=paciente,
            fecha=paciente.fecha_ultima_consulta or date.today(),
            peso=paciente.peso,
            talla=paciente.talla,
            pliegue_1=paciente.pliegue_1,
            pliegue_2=paciente.pliegue_2,
            pliegue_3=paciente.pliegue_3,
            actividad_fisica=paciente.actividad_fisica,
        )
        Plan.objects.filter(paciente=paciente, medicion__isnull=True).update(medicion=medicion)


def revertir(apps, schema_editor):
    Medicion = apps.get_model('api', 'Medicion')
    Medicion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medicion_plan_medicion'),
    ]

    operations = [
        migrations.RunPython(crear_medicion_inicial, revertir),
    ]
