# Generated by Django 6.1 on 2026-08-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_paciente_actividad_fisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='calorias_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Calorias del plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='carbohidratos_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Carbohidratos del plan'),
        ),
    ]
