# Generated by Django 6.1 on 2026-08-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_plan_calorias_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cantidad_agua',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cantidad de agua'),
        ),
    ]
