# Generated by Django 6.1 on 2026-08-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_plan_cantidad_agua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='potasio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='sodio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
