# Generated by Django 6.1 on 2026-08-15 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tiempocomida_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='medicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='api.medicion'),
        ),
    ]
