# Generated by Django 6.1 on 2026-08-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_ultima_consulta', models.DateField(blank=True, null=True)),
                ('restricciones_alimentarias', models.TextField(blank=True, default='', verbose_name='Restricciones alimentarias')),
                ('alergias_alimentarias', models.TextField(blank=True, default='', verbose_name='Alergias alimentarias')),
                ('enfermedades_existentes', models.TextField(blank=True, default='', verbose_name='Enfermedades existentes')),
                ('medicamentos_actuales', models.TextField(blank=True, default='', verbose_name='Medicamentos actuales')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'Ninguno')], default='N', max_length=1)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pliegue_1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pliegue_2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pliegue_3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad_fisica', models.CharField(choices=[('1.2', 'Sedentario (sin ejercicio)'), ('1.375', 'Ligero (ejercicio 1-3 días a la semana)'), ('1.55', 'Moderado (ejercicio 3-5 días a la semana)'), ('1.725', 'Muy activo (ejercicio 6-7 días a la semana)'), ('1.9', 'Extremadamente activo (ejercicio intenso 2 veces al día)')], default='1.2', max_length=5)),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
            ],
        ),
    ]
