# Generated by Django 6.1 on 2026-08-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteina', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grasa_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fibra', models.DecimalField(decimal_places=2, max_digits=6)),
                ('azucares', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grasa_saturada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grasas_trans', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sodio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('potasio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('es_local', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('preparacion', models.TextField(blank=True, default='', verbose_name='Preparacion')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_plan', models.TextField(blank=True, default='', verbose_name='Objetivo del plan')),
                ('calorias_objetivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Calorias del plan')),
                ('proteinas_objetivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Proteinas del plan')),
                ('carbohidratos_objetivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Carbohidratos del plan')),
                ('grasas_objetivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Grasas del plan')),
                ('cantidad_agua', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Cantidad de agua')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='api.plato')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DES', 'Desayuno'), ('MM', 'Media Mañana'), ('ALM', 'Almuerzo'), ('MT', 'Media Tarde'), ('CEN', 'Cena')], max_length=3)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='api.plan')),
                ('platos', models.ManyToManyField(related_name='comidas', to='api.plato')),
            ],
        ),
    ]
