# Generated by Django 6.1 on 2026-08-07 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_migrar_datos_paciente_a_medicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='actividad_fisica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_ultima_consulta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pliegue_1',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pliegue_2',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='pliegue_3',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='plan',
            name='medicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='api.medicion'),
        ),
    ]
