# Generated by Django 6.1 on 2026-08-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ingrediente_potasio_alter_ingrediente_sodio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiempocomida',
            options={'ordering': [models.Case(models.When(then=models.Value(1), tipo='DES'), models.When(then=models.Value(2), tipo='MM'), models.When(then=models.Value(3), tipo='ALM'), models.When(then=models.Value(4), tipo='MT'), models.When(then=models.Value(5), tipo='CEN'), output_field=models.IntegerField())]},
        ),
    ]
