"""
Django settings for kuna project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En desarrollo cae al valor por defecto; en cualquier despliegue real hay
# que definir DJANGO_SECRET_KEY en el entorno.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-solo-para-desarrollo-local-no-usar-en-produccion",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

def _lista_de_entorno(variable, por_defecto=""):
    """Lee una variable de entorno separada por comas y descarta los vacios."""
    return [item.strip() for item in os.environ.get(variable, por_defecto).split(",") if item.strip()]


ALLOWED_HOSTS = _lista_de_entorno("DJANGO_ALLOWED_HOSTS")

# Render publica el dominio del servicio en esta variable; lo agregamos solo.
_host_render = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _host_render:
    ALLOWED_HOSTS.append(_host_render)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'corsheaders',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kuna.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kuna.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# En local cae a SQLite; en produccion se define DATABASE_URL (Neon).
# conn_health_checks es lo que sostiene las conexiones persistentes frente al
# scale-to-zero de Neon: Django verifica la conexion antes de reutilizarla y
# reconecta si el servidor se durmio, en lugar de fallar la primera consulta.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# El endpoint "-pooler" de Neon es PgBouncer en modo transaccion: la conexion
# vuelve al pool al terminar cada transaccion, asi que un cursor del lado del
# servidor no sobrevive hasta la siguiente. Se detecta por el host para que la
# cadena de conexion siga siendo lo unico que haya que configurar.
if "-pooler" in (DATABASES["default"].get("HOST") or ""):
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise sirve los estaticos del admin, comprimidos y con hash en el nombre.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Origenes del frontend habilitados para consumir la API.
CORS_ALLOWED_ORIGINS = _lista_de_entorno(
    "DJANGO_CORS_ALLOWED_ORIGINS", "http://localhost:5173"
)

# Necesario para poder autenticarse en el admin sobre HTTPS.
CSRF_TRUSTED_ORIGINS = _lista_de_entorno("DJANGO_CSRF_TRUSTED_ORIGINS")

# Render termina el TLS en su proxy: sin esto Django cree que la conexion es HTTP.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Endurecimiento para produccion. Se activa solo cuando DEBUG esta apagado, para
# no romper el servidor de desarrollo, que habla HTTP plano.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS acotado a este host: sin includeSubDomains ni preload, porque el
    # dominio es compartido y esa decision no seria facil de revertir.
    SECURE_HSTS_SECONDS = 3600

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
}
